# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]        
  release:
    types: [created]

    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Yarn Setup
        # You may pin to the exact commit or the version.
        # uses: DerYeger/yarn-setup-action@f55be5383ea94f5eb25b20aee609af4603a68dde
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          # The version of Node.js that will be used
          node-version: ${{ matrix.node }}    
          
      - name: Run build
        run: |
          yarn install
          yarn build
          
      - name: NPM Release Pack
        # You may pin to the exact commit or the version.
        # uses: LumaKernel/npm-release-pack-action@a409510f3c988cfa63ecc61995dc0de7d57a3642
        uses: LumaKernel/npm-release-pack-action@v1.0.1
        with:
          # GitHub token or PAT token
          github_token: ${{ github.token }}
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          # repository: # optional, default is 
          # Directory to publish.
          working_directory: ./dist
#           # Command to publish.
#           publish_command: 
#           # Version tag pattern with %s. Multiple %s is allowed. Cannot use percent charcter.
#           version_tag_pattern: # optional, default is v%s
#           # GitHub release name pattern with %s. Multiple %s is allowed. Cannot use percent charcter.
#           release_name_pattern: # optional, default is v%s
#           # GitHub release body.
#           release_body: # optional
#           # GitHub release draft.
#           draft: # optional
#           # GitHub release prerelease.
#           prerelease: # optional
#           # GitHub release generate_release_notes.
#           generate_release_notes: # optional
#           # GitHub release discussion_category_name.
#           discussion_category_name: # optional
            
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  
